/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pricedisplay_app;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void CheckingForCorrectResult() {
        App label = new App();
        assertEquals("Returns correct result", String.format("The price for item: Cookie is £0.99"),label.GetPriceLabel("Cookie",0.99) );
    }   
}
