/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pricedisplay_app;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public String GetPriceLabel(String a, Double b) {

        return String.format("The price for item: %s is £%.2f",a, b);
    }
}
