/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

public class App {

    static ArrayList<Game> Current_Games = new ArrayList<Game>();

    public String getGreeting() {
        return "Greeting";
    }
    

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.println("Enter name for player 1");
        String name_1 = scanner.nextLine();
        WordChoser choser_1 = new WordChoser();
        Current_Games.add(new Game(choser_1,name_1));

        System.out.println("Enter name for player 2");
        String name_2 = scanner.nextLine();
        WordChoser choser_2 = new WordChoser();
        Current_Games.add(new Game(choser_2,name_2));

        Random starter = new Random();
        int currentPlayer = starter.nextInt(2);

        System.out.println("Welcome! Today the word to guess is:");
        System.out.printf("%s : %s\n",Current_Games.get(0).getName(),Current_Games.get(0).GetWordToGuess());

        System.out.printf("%s : %s\n",Current_Games.get(1).getName(),Current_Games.get(1).GetWordToGuess());
        

        while (EitherPlayerWinOrLose() == false) {
            System.out.println("");
            System.out.printf("It is %s's turn now.\n",Current_Games.get(currentPlayer).getName());
            System.out.println(Current_Games.get(currentPlayer).GetWordToGuess());
            System.out.printf("%s: Enter one letter to guess (%s attempts remaining):\n",Current_Games.get(currentPlayer).getName(), Current_Games.get(currentPlayer).getRemainingAttempts());
            Character guess = scanner.nextLine().charAt(0);
            Boolean result = Current_Games.get(currentPlayer).guessLetter(guess);
            if (result) {
                System.out.println("Right!");
                System.out.println(Current_Games.get(currentPlayer).GetWordToGuess());
            }
            else {
                System.out.println("Wrong...");
            }
            if (currentPlayer == 1) {
                currentPlayer = 0;
                
            }else {
                currentPlayer = 1;
            }
        }

        System.out.println("THE GAME HAS ENDED.");
        if (Current_Games.get(0).isGameWon() || Current_Games.get(1).isGameLost()) {
            System.out.printf("The winner is %s. \n",Current_Games.get(0).getName());
        }
        else{
            System.out.printf("The winner is %s. \n",Current_Games.get(1).getName());
        }
        System.out.println("Thanks for playing!");
        //while (EitherPlayerWinOrLose() == false) {
        //    System.out.println(game.GetWordToGuess());
        //    System.out.printf("Enter one letter to guess (%s attempts remaining) \n",game.getRemainingAttempts().toString());
        //    Scanner scanner = new Scanner(System.in);
        //    Character guess = scanner.nextLine().charAt(0);
        //    Boolean result = game.guessLetter(guess);

        //    if (result) {
        //        System.out.println("Right!");
        //    }
        //    else {
        //        System.out.println("Wrong...");
        //    }
        //}
        //if (game.isGameLost()) {
        //    System.out.println("You ran out of attempts and lost!");
        //}
        //if (game.isGameWon()) {
        //    System.out.println("Well done! You got it correct and won!");
        //}
        

        //ArrayList<Character> guessed_letters = new ArrayList<Character>();
        //System.out.println(new App().getGreeting());
        //Game game = new Game("MAKERS");
        //game.main(args);
        //guessed_letters.add('A');
        //guessed_letters.add('D');
        //System.out.println(guessed_letters.indexOf('Q'));
        
        scanner.close();
    }

    public static Boolean EitherPlayerWinOrLose() {
        if (Current_Games.get(0).isGameLost() || Current_Games.get(1).isGameLost()) {
            return true;
        }
        if (Current_Games.get(0).isGameWon() || Current_Games.get(1).isGameWon()) {
            return true;
        }
        return false;
    }
}
